import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'ar', name: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  { code: 'en', name: 'English', flag: '🇬🇧', dir: 'ltr' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷', dir: 'ltr' },
  { code: 'fr', name: 'Français', flag: '🇫🇷', dir: 'ltr' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺', dir: 'ltr' },
  { code: 'es', name: 'Español', flag: '🇪🇸', dir: 'ltr' },
  { code: 'ur', name: 'اردو', flag: '🇵🇰', dir: 'rtl' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹', dir: 'ltr' },
];

const translations = {
  ar: {
    // Nav & General
    home: 'الرئيسية',
    collection: 'التشكيلة',
    showcase: 'معرضنا',
    magazine: 'مجلة زهرة بيسان',
    giftCards: 'بطاقات الهدايا',
    contact: 'اتصلي بنا',
    trackOrder: 'تتبع الطلب',
    cart: 'حقيبة التسوق',
    wishlist: 'المفضلة',
    searchPlaceholder: 'ابحثي عن اسم العباية، التطريز، أو اللون...',
    allAbayas: 'جميع العبايا',
    featuredCollection: 'التشكيلة المختارة',
    exclusiveCreations: 'إبداعاتنا الحصرية',
    details: 'تفاصيل',
    addToCart: 'أضف للسلة',
    buyNow: 'اطلب الآن',
    outOfStock: 'نفذت الكمية',
    originalColor: 'اللون الأصلي',
    color: 'اللون',
    size: 'المقاس',
    sizeGuide: '📏 دليل ومساعد المقاسات الذكي',
    productDesc: 'وصف المنتج',
    weightForSize: '⚖️ الوزن للمقاس',
    relatedProducts: 'قد يعجبك أيضاً',
    customerReviews: 'آراء العملاء',
    noReviewsYet: 'لا توجد تقييمات بعد. كوني أول من يقيّم هذا المنتج!',
    writeReview: '✍️ اكتبي تقييمك',
    submitReview: 'إرسال التقييم',
    yourRating: 'تقييمك:',
    submitting: 'جاري الإرسال...',
    reviewSuccess: '✓ شكراً! تم إرسال تقييمك بنجاح.',
    aiVideoGenerator: '✨ توليد فيديو سينمائي AI (12-15ث)',
    generatingVideo: '🎬 جاري توليد الفيديو السينمائي بالأذكاء الاصطناعي...',
    videoReady: '✓ تم توليد الفيديو بنجاح!',
  },
  en: {
    home: 'Home',
    collection: 'Collection',
    showcase: 'Showcase',
    magazine: 'Beesan Magazine',
    giftCards: 'Gift Cards',
    contact: 'Contact Us',
    trackOrder: 'Track Order',
    cart: 'Shopping Bag',
    wishlist: 'Wishlist',
    searchPlaceholder: 'Search by abaya name, embroidery, or color...',
    allAbayas: 'All Abayas',
    featuredCollection: 'Featured Collection',
    exclusiveCreations: 'Our Exclusive Creations',
    details: 'Details',
    addToCart: 'Add to Cart',
    buyNow: 'Buy Now',
    outOfStock: 'Out of Stock',
    originalColor: 'Original Color',
    color: 'Color',
    size: 'Size',
    sizeGuide: '📏 Smart Size Guide & Helper',
    productDesc: 'Product Description',
    weightForSize: '⚖️ Weight for Size',
    relatedProducts: 'You May Also Like',
    customerReviews: 'Customer Reviews',
    noReviewsYet: 'No reviews yet. Be the first to review this product!',
    writeReview: '✍️ Write Your Review',
    submitReview: 'Submit Review',
    yourRating: 'Your Rating:',
    submitting: 'Submitting...',
    reviewSuccess: '✓ Thank you! Your review has been submitted.',
    aiVideoGenerator: '✨ Generate AI Cinematic Video (12-15s)',
    generatingVideo: '🎬 Generating AI cinematic video...',
    videoReady: '✓ Video generated successfully!',
  },
  tr: {
    home: 'Anasayfa',
    collection: 'Koleksiyon',
    showcase: 'Galeri',
    magazine: 'Beesan Dergisi',
    giftCards: 'Hediye Kartları',
    contact: 'İletişim',
    trackOrder: 'Sipariş Takibi',
    cart: 'Alışveriş Çantası',
    wishlist: 'Favorilerim',
    searchPlaceholder: 'Abaye adı, nakış veya renk arayın...',
    allAbayas: 'Tüm Abayeler',
    featuredCollection: 'Öne Çıkan Koleksiyon',
    exclusiveCreations: 'Özel Tasarımlarımız',
    details: 'Detaylar',
    addToCart: 'Sepete Ekle',
    buyNow: 'Hemen Satın Al',
    outOfStock: 'Stokta Yok',
    originalColor: 'Orijinal Renk',
    color: 'Renk',
    size: 'Beden',
    sizeGuide: '📏 Akıllı Beden Rehberi',
    productDesc: 'Ürün Açıklaması',
    weightForSize: '⚖️ Beden Ağırlığı',
    relatedProducts: 'Bunları da Beğenebilirsiniz',
    customerReviews: 'Müşteri Değerlendirmeleri',
    noReviewsYet: 'Henüz değerlendirme yok. İlk değerlendiren siz olun!',
    writeReview: '✍️ Değerlendirmenizi Yazın',
    submitReview: 'Gönder',
    yourRating: 'Puanınız:',
    submitting: 'Gönderiliyor...',
    reviewSuccess: '✓ Teşekkürler! Değerlendirmeniz alındı.',
    aiVideoGenerator: '✨ Yapay Zeka Sinematik Video Oluştur (12-15s)',
    generatingVideo: '🎬 Sinematik video oluşturuluyor...',
    videoReady: '✓ Video başarıyla oluşturuldu!',
  },
  fr: {
    home: 'Accueil',
    collection: 'Collection',
    showcase: 'Galerie',
    magazine: 'Magazine Beesan',
    giftCards: 'Cartes Cadeaux',
    contact: 'Contactez-nous',
    trackOrder: 'Suivre ma commande',
    cart: 'Panier',
    wishlist: 'Favoris',
    searchPlaceholder: 'Rechercher par nom d\'abaya, broderie ou couleur...',
    allAbayas: 'Toutes les Abayas',
    featuredCollection: 'Collection En Vedette',
    exclusiveCreations: 'Nos Créations Exclusives',
    details: 'Détails',
    addToCart: 'Ajouter au Panier',
    buyNow: 'Acheter Maintenant',
    outOfStock: 'Rupture de Stock',
    originalColor: 'Couleur d\'Origine',
    color: 'Couleur',
    size: 'Taille',
    sizeGuide: '📏 Guide des Tailles Intelligent',
    productDesc: 'Description du Produit',
    weightForSize: '⚖️ Poids par Taille',
    relatedProducts: 'Vous Aimerez Aussi',
    customerReviews: 'Avis Clients',
    noReviewsYet: 'Aucun avis pour le moment. Soyez la première à donner votre avis !',
    writeReview: '✍️ Écrire un Avis',
    submitReview: 'Soumettre l\'Avis',
    yourRating: 'Votre Note :',
    submitting: 'Envoi en cours...',
    reviewSuccess: '✓ Merci ! Votre avis a été soumis.',
    aiVideoGenerator: '✨ Générer Vidéo Cinématique IA (12-15s)',
    generatingVideo: '🎬 Génération de la vidéo en cours...',
    videoReady: '✓ Vidéo générée avec succès !',
  },
  de: {
    home: 'Startseite',
    collection: 'Kollektion',
    showcase: 'Galerie',
    magazine: 'Beesan Magazin',
    giftCards: 'Gutscheine',
    contact: 'Kontakt',
    trackOrder: 'Bestellung Verfolgen',
    cart: 'Warenkorb',
    wishlist: 'Wunschliste',
    searchPlaceholder: 'Suche nach Abaya-Name, Stickerei oder Farbe...',
    allAbayas: 'Alle Abayas',
    featuredCollection: 'Ausgewählte Kollektion',
    exclusiveCreations: 'Unsere Exklusiven Kreationen',
    details: 'Details',
    addToCart: 'In den Warenkorb',
    buyNow: 'Jetzt Kaufen',
    outOfStock: 'Ausverkauft',
    originalColor: 'Originalfarbe',
    color: 'Farbe',
    size: 'Größe',
    sizeGuide: '📏 Intelligenter Größenguide',
    productDesc: 'Produktbeschreibung',
    weightForSize: '⚖️ Gewicht nach Größe',
    relatedProducts: 'Das Könnte Ihnen Auch Gefallen',
    customerReviews: 'Kundenbewertungen',
    noReviewsYet: 'Noch keine Bewertungen. Seien Sie die Erste!',
    writeReview: '✍️ Bewertung Schreiben',
    submitReview: 'Bewertung Absenden',
    yourRating: 'Ihre Bewertung:',
    submitting: 'Wird gesendet...',
    reviewSuccess: '✓ Vielen Dank! Ihre Bewertung wurde übermittelt.',
    aiVideoGenerator: '✨ KI-Kinovideo Erstellen (12-15s)',
    generatingVideo: '🎬 KI-Video wird erstellt...',
    videoReady: '✓ Video erfolgreich erstellt!',
  },
  ru: {
    home: 'Главная',
    collection: 'Коллекция',
    showcase: 'Галерея',
    magazine: 'Журнал Beesan',
    giftCards: 'Подарочные карты',
    contact: 'Контакты',
    trackOrder: 'Отследить заказ',
    cart: 'Корзина',
    wishlist: 'Избранное',
    searchPlaceholder: 'Поиск по названию абайи, вышивке или цвету...',
    allAbayas: 'Все Абайи',
    featuredCollection: 'Рекомендуемая коллекция',
    exclusiveCreations: 'Наши Эксклюзивные Модели',
    details: 'Подробнее',
    addToCart: 'В корзину',
    buyNow: 'Купить сейчас',
    outOfStock: 'Нет в наличии',
    originalColor: 'Исходный цвет',
    color: 'Цвет',
    size: 'Размер',
    sizeGuide: '📏 Умный гид по размерам',
    productDesc: 'Описание товара',
    weightForSize: '⚖️ Вес для размера',
    relatedProducts: 'Вам также может понравиться',
    customerReviews: 'Отзывы покупателей',
    noReviewsYet: 'Отзывов пока нет. Будьте первыми!',
    writeReview: '✍️ Написать отзыв',
    submitReview: 'Отправить отзыв',
    yourRating: 'Ваша оценка:',
    submitting: 'Отправка...',
    reviewSuccess: '✓ Спасибо! Ваш отзыв успешно отправлен.',
    aiVideoGenerator: '✨ Создать ИИ-видео (12-15с)',
    generatingVideo: '🎬 Создание видео ИИ...',
    videoReady: '✓ Видео успешно создано!',
  },
  es: {
    home: 'Inicio',
    collection: 'Colección',
    showcase: 'Galería',
    magazine: 'Revista Beesan',
    giftCards: 'Tarjetas de Regalo',
    contact: 'Contacto',
    trackOrder: 'Rastrear Pedido',
    cart: 'Bolsa de Compras',
    wishlist: 'Lista de Deseos',
    searchPlaceholder: 'Buscar por nombre de abaya, bordado o color...',
    allAbayas: 'Todas las Abayas',
    featuredCollection: 'Colección Destacada',
    exclusiveCreations: 'Nuestras Creaciones Exclusivas',
    details: 'Detalles',
    addToCart: 'Añadir al Carrito',
    buyNow: 'Comprar Ahora',
    outOfStock: 'Agotado',
    originalColor: 'Color Original',
    color: 'Color',
    size: 'Talla',
    sizeGuide: '📏 Guía Inteligente de Tallas',
    productDesc: 'Descripción del Producto',
    weightForSize: '⚖️ Peso por Talla',
    relatedProducts: 'También Te Puede Gustar',
    customerReviews: 'Opiniones de Clientes',
    noReviewsYet: 'Aún no hay opiniones. ¡Sé la primera en opinar!',
    writeReview: '✍️ Escribir una Opinión',
    submitReview: 'Enviar Opinión',
    yourRating: 'Tu Valoración:',
    submitting: 'Enviando...',
    reviewSuccess: '✓ ¡Gracias! Tu opinión ha sido enviada.',
    aiVideoGenerator: '✨ Generar Video IA Cinematográfico (12-15s)',
    generatingVideo: '🎬 Generando video cinematográfico IA...',
    videoReady: '✓ ¡Video generado con éxito!',
  },
  ur: {
    home: 'ہوم',
    collection: 'کلیکشن',
    showcase: 'گئیلری',
    magazine: 'بیسان میگزین',
    giftCards: 'گفٹ کارڈز',
    contact: 'ہم سے رابطہ کریں',
    trackOrder: 'آرڈر ٹریک کریں',
    cart: 'خریداری کا تھیلا',
    wishlist: 'پسندیدہ',
    searchPlaceholder: 'عبایا کے نام، کڑھائی یا رنگ سے تلاش کریں...',
    allAbayas: 'تمام عبایاجات',
    featuredCollection: 'خاص کلیکشن',
    exclusiveCreations: 'ہماری خصوصیات',
    details: 'تفصیلات',
    addToCart: 'کارٹ میں شامل کریں',
    buyNow: 'ابھی خریدیں',
    outOfStock: 'اسٹاک میں نہیں ہے',
    originalColor: 'اصل رنگ',
    color: 'رنگ',
    size: 'سائز',
    sizeGuide: '📏 سائز گائیڈ',
    productDesc: 'پروڈکٹ کی تفصیل',
    weightForSize: '⚖️ سائز کا وزن',
    relatedProducts: 'آپ کو یہ بھی پسند آ سکتا ہے',
    customerReviews: 'کسٹمر کے جائزے',
    noReviewsYet: 'ابھی تک کوئی جائزے۔ پہلے جائزہ نگار بنیں!',
    writeReview: '✍️ اپنا جائزہ لکھیں',
    submitReview: 'جائزہ جمع کروائیں',
    yourRating: 'آپ کی درجہ بندی:',
    submitting: 'ارسال ہو رہا ہے...',
    reviewSuccess: '✓ شکریہ! آپ کا جائزہ جمع کر دیا گیا ہے۔',
    aiVideoGenerator: '✨ AI سنیمیٹک ویڈیو بنائیں۔ (12-15 سیکنڈ)',
    generatingVideo: '🎬 ویڈیو بنائی جا رہی ہے...',
    videoReady: '✓ ویڈیو کامیابی سے بن گئی!',
  },
  it: {
    home: 'Home',
    collection: 'Collezione',
    showcase: 'Galleria',
    magazine: 'Rivista Beesan',
    giftCards: 'Carte Regalo',
    contact: 'Contattaci',
    trackOrder: 'Traccia Ordine',
    cart: 'Carrello',
    wishlist: 'Lista dei Desideri',
    searchPlaceholder: 'Cerca per nome abaya, ricamo o colore...',
    allAbayas: 'Tutte le Abaya',
    featuredCollection: 'Collezione In Evidenza',
    exclusiveCreations: 'Le Nostre Creazioni Esclusive',
    details: 'Dettagli',
    addToCart: 'Aggiungi al Carrello',
    buyNow: 'Acquista Ora',
    outOfStock: 'Esaurito',
    originalColor: 'Colore Originale',
    color: 'Colore',
    size: 'Taglia',
    sizeGuide: '📏 Guida Intelligente alle Taglie',
    productDesc: 'Descrizione Prodotto',
    weightForSize: '⚖️ Peso per Taglia',
    relatedProducts: 'Potrebbe Piacerti Anche',
    customerReviews: 'Recensioni Clienti',
    noReviewsYet: 'Nessuna recensione. Sii la prima a recensire questo prodotto!',
    writeReview: '✍️ Scrivi una Recensione',
    submitReview: 'Invia Recensione',
    yourRating: 'La Tua Valutazione:',
    submitting: 'Invio in corso...',
    reviewSuccess: '✓ Grazie! La tua recensione è stata inviata.',
    aiVideoGenerator: '✨ Genera Video IA Cinematografico (12-15s)',
    generatingVideo: '🎬 Generazione video IA in corso...',
    videoReady: '✓ Video generato con successo!',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [langCode, setLangCode] = useState(() => {
    return localStorage.getItem('app_language') || 'ar';
  });

  const currentLang = LANGUAGES.find(l => l.code === langCode) || LANGUAGES[0];

  useEffect(() => {
    localStorage.setItem('app_language', langCode);
    document.documentElement.lang = langCode;
    document.documentElement.dir = currentLang.dir;
  }, [langCode, currentLang]);

  const t = (key) => {
    return translations[langCode]?.[key] || translations['ar']?.[key] || key;
  };

  const changeLanguage = (code) => {
    if (LANGUAGES.some(l => l.code === code)) {
      setLangCode(code);
    }
  };

  return (
    <LanguageContext.Provider value={{ langCode, currentLang, changeLanguage, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
