import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'ar', name: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  { code: 'en', name: 'English', flag: '🇬🇧', dir: 'ltr' }
];

const translations = {
  ar: {
    // Nav & General
    home: 'الرئيسية',
    collection: 'التشكيلة',
    showcase: 'معرضنا',
    magazine: 'مجلة زهرة بيسان',
    giftCards: 'بطاقات الهدايا',
    contact: 'اتصلي بنا',
    trackOrder: 'تتبع الطلب',
    cart: 'حقيبة التسوق',
    wishlist: 'المفضلة',
    searchPlaceholder: 'ابحثي عن اسم العباية، التطريز، أو اللون...',
    allAbayas: 'جميع العبايا',
    featuredCollection: 'التشكيلة المختارة',
    exclusiveCreations: 'إبداعاتنا الحصرية',
    details: 'تفاصيل',
    addToCart: 'أضف للسلة',
    buyNow: 'اطلب الآن',
    outOfStock: 'نفذت الكمية',
    originalColor: 'اللون الأصلي',
    color: 'اللون',
    size: 'المقاس',
    sizeGuide: '📏 دليل ومساعد المقاسات الذكي',
    productDesc: 'وصف المنتج',
    weightForSize: '⚖️ الوزن للمقاس',
    relatedProducts: 'قد يعجبك أيضاً',
    customerReviews: 'آراء العملاء',
    noReviewsYet: 'لا توجد تقييمات بعد. كوني أول من يقيّم هذا المنتج!',
    writeReview: '✍️ اكتبي تقييمك',
    submitReview: 'إرسال التقييم',
    yourRating: 'تقييمك:',
    submitting: 'جاري الإرسال...',
    reviewSuccess: '✓ شكراً! تم إرسال تقييمك بنجاح.',
    aiVideoGenerator: '✨ توليد فيديو سينمائي AI (12-15ث)',
    generatingVideo: '🎬 جاري توليد الفيديو السينمائي بالأذكاء الاصطناعي...',
    videoReady: '✓ تم توليد الفيديو بنجاح!',
    // Section Titles & Badges
    bestSellers: 'الأكثر مبيعاً',
    mostRequested: 'الأكثر طلباً',
    bestSellersDesc: 'التشكيلات الأكثر إقبالاً من عملائنا الكرام',
    whatCustomersSay: 'ماذا يقول عملاؤنا',
    viewAll: 'عرض الكل',
    expressShipping: 'شحن عالمي',
    expressShippingDesc: 'نوصل لجميع أنحاء العالم',
    premiumQuality: 'جودة مضمونة',
    premiumQualityDesc: 'خامات فاخرة وعالية الجودة',
    securePayment: 'دفع آمن',
    securePaymentDesc: 'جميع وسائل الدفع متاحة',
    easyReturns: 'سهولة الإرجاع',
    easyReturnsDesc: 'سياسة إرجاع مرنة وسهلة',
    // Footer & Links
    quickLinks: 'روابط سريعة',
    contactUs: 'تواصل معنا',
    newsletter: 'النشرة البريدية',
    newsletterDesc: 'اشتركي لتصلكِ العروض الحصرية:',
    emailPlaceholder: 'بريدكِ الإلكتروني',
    subscribe: 'اشتراك',
    subscribeSuccess: 'تم الاشتراك في النشرة البريدية بنجاح!',
    brandTagline: 'زهرة بيسان — تصاميم حصرية وخامات فاخرة تعكس الأصالة والوقار. نوصّل لجميع دول العالم.',
    allRightsReserved: 'جميع الحقوق محفوظة © زهرة بيسان',
    whatsapp: 'واتساب',
    aboutUs: 'نبذة عنّا',
    faq: 'الأسئلة الشائعة',
    gallery: 'معرض الصور',
    internationalDelivery: 'توصيل دولي',
    secureCheckout: 'دفع آمن',
    easyExchange: 'تبديل محلي',
    // Cart
    emptyCart: 'السلة فارغة',
    emptyCartDesc: 'يبدو أنكِ لم تضيفي أي منتجات إلى سلتكِ بعد.',
    startShopping: 'ابدئي التسوق',
    piece: 'قطعة',
    pieces: 'قطع',
    sizeLabel: 'المقاس',
    sendAsGift: '🎁 إرسال كهدية ملكية لشخص عزيز',
    giftDesc: 'تتضمن الهدية تغليفاً عاجياً فاخراً ومعطراً بعطر بيسان، مع طباعة كارت الإهداء الملكي.',
    giftMsgPlaceholder: 'اكتبي رسالة الإهداء الخاصة ليتم طباعتها على كارت الإهداء...',
    hidePrices: 'إخفاء أسعار المنتجات بالفاتورة عن المستلم',
    subtotal: 'المجموع الفرعي',
    bundleDiscountLabel: 'خصم الباقة (10%)',
    deliveryFee: 'رسوم التوصيل',
    calcAtCheckout: 'يُحسب في الدفع',
    totalLabel: 'المجموع الكلي',
    confirmOrder: 'تأكيد الطلب',
    clearCart: 'إفراغ السلة',
    deliveryNoteCart: 'يتم حساب رسوم التوصيل بدقة في صفحة الدفع.',
    // Wishlist
    wishlistTitle: 'قائمة الأمنيات',
    productSingular: 'منتج',
    productPlural: 'منتجات',
    emptyWishlist: 'لا توجد منتجات في المفضلة',
    emptyWishlistDesc: 'ابدئي بإضافة منتجات إلى قائمة أمنياتك',
    moveToCart: 'أضف للسلة',
    removeItem: 'إزالة',
    clearWishlist: 'مسح الكل',
    // Product Modal
    photosTab: 'صور',
    videoTab: 'فيديو',
    availableColors: 'الألوان المتاحة',
    selectSize: 'اختاري المقاس',
    quantityLabel: 'الكمية',
    shareProduct: 'مشاركة المنتج',
    copiedLink: '✓ تم نسخ الرابط!',
    contactWhatsApp: 'تواصلي عبر الواتساب',
    addedToCart: 'تمت الإضافة إلى السلة!',
    addedToWishlist: 'تمت الإضافة إلى المفضلة!',
    removedFromWishlist: 'تم الحذف من المفضلة',
    selectSizeFirst: 'الرجاء اختيار المقاس أولاً',
    // General
    closeLabel: 'إغلاق',
    save: 'حفظ',
    cancel: 'إلغاء',
    loading: 'جاري التحميل...',
    error: 'حدث خطأ',
    success: 'تم بنجاح'
  },
  en: {
    home: 'Home',
    collection: 'Collection',
    showcase: 'Showcase',
    magazine: 'Beesan Magazine',
    giftCards: 'Gift Cards',
    contact: 'Contact Us',
    trackOrder: 'Track Order',
    cart: 'Shopping Bag',
    wishlist: 'Wishlist',
    searchPlaceholder: 'Search by abaya name, embroidery, or color...',
    allAbayas: 'All Abayas',
    featuredCollection: 'Featured Collection',
    exclusiveCreations: 'Our Exclusive Creations',
    details: 'Details',
    addToCart: 'Add to Cart',
    buyNow: 'Buy Now',
    outOfStock: 'Out of Stock',
    originalColor: 'Original Color',
    color: 'Color',
    size: 'Size',
    sizeGuide: '📏 Smart Size Guide & Helper',
    productDesc: 'Product Description',
    weightForSize: '⚖️ Weight for Size',
    relatedProducts: 'You May Also Like',
    customerReviews: 'Customer Reviews',
    noReviewsYet: 'No reviews yet. Be the first to review this product!',
    writeReview: '✍️ Write Your Review',
    submitReview: 'Submit Review',
    yourRating: 'Your Rating:',
    submitting: 'Submitting...',
    reviewSuccess: '✓ Thank you! Your review has been submitted.',
    aiVideoGenerator: '✨ Generate AI Cinematic Video (12-15s)',
    generatingVideo: '🎬 Generating AI cinematic video...',
    videoReady: '✓ Video generated successfully!',
    bestSellers: 'Best Sellers',
    mostRequested: 'Most Popular',
    bestSellersDesc: 'Top-rated collections loved by our esteemed clients',
    whatCustomersSay: 'What Our Customers Say',
    viewAll: 'View All',
    expressShipping: 'Worldwide Shipping',
    expressShippingDesc: 'We deliver all over the world',
    premiumQuality: 'Guaranteed Quality',
    premiumQualityDesc: 'Luxurious and premium fabrics',
    securePayment: 'Secure Payment',
    securePaymentDesc: 'All payment methods available',
    easyReturns: 'Easy Returns',
    easyReturnsDesc: 'Flexible & easy return policy',
    quickLinks: 'Quick Links',
    contactUs: 'Contact Us',
    newsletter: 'Newsletter',
    newsletterDesc: 'Subscribe for exclusive offers:',
    emailPlaceholder: 'Your Email Address',
    subscribe: 'Subscribe',
    subscribeSuccess: 'Successfully subscribed to our newsletter!',
    brandTagline: 'Zahrat Beesan — Exclusive designs and luxurious fabrics reflecting elegance. Worldwide delivery.',
    allRightsReserved: 'All rights reserved © Zahrat Beesan',
    whatsapp: 'WhatsApp',
    aboutUs: 'About Us',
    faq: 'FAQ',
    gallery: 'Gallery',
    internationalDelivery: 'Global Delivery',
    secureCheckout: 'Secure Checkout',
    easyExchange: 'Easy Exchange',
    // Cart
    emptyCart: 'Your Bag is Empty',
    emptyCartDesc: 'You have not added any items to your bag yet.',
    startShopping: 'Start Shopping',
    piece: 'item',
    pieces: 'items',
    sizeLabel: 'Size',
    sendAsGift: '🎁 Send as a Royal Gift',
    giftDesc: 'Includes luxury ivory packaging, Beesan perfume, and a printed royal gift card.',
    giftMsgPlaceholder: 'Write your personal gift message to be printed on the gift card...',
    hidePrices: 'Hide product prices from recipient invoice',
    subtotal: 'Subtotal',
    bundleDiscountLabel: 'Bundle Discount (10%)',
    deliveryFee: 'Delivery Fee',
    calcAtCheckout: 'Calculated at checkout',
    totalLabel: 'Total',
    confirmOrder: 'Confirm Order',
    clearCart: 'Clear Bag',
    deliveryNoteCart: 'Delivery fees are calculated precisely at checkout.',
    // Wishlist
    wishlistTitle: 'Wishlist',
    productSingular: 'item',
    productPlural: 'items',
    emptyWishlist: 'Your wishlist is empty',
    emptyWishlistDesc: 'Start adding products to your wishlist',
    moveToCart: 'Add to Bag',
    removeItem: 'Remove',
    clearWishlist: 'Clear All',
    // Product Modal
    photosTab: 'Photos',
    videoTab: 'Video',
    availableColors: 'Available Colors',
    selectSize: 'Select Size',
    quantityLabel: 'Quantity',
    shareProduct: 'Share Product',
    copiedLink: '✓ Link Copied!',
    contactWhatsApp: 'Contact via WhatsApp',
    addedToCart: 'Added to bag!',
    addedToWishlist: 'Added to wishlist!',
    removedFromWishlist: 'Removed from wishlist',
    selectSizeFirst: 'Please select a size first',
    // General
    closeLabel: 'Close',
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading...',
    error: 'An error occurred',
    success: 'Success'
  },
  tr: {
    home: 'Anasayfa',
    collection: 'Koleksiyon',
    showcase: 'Galeri',
    magazine: 'Beesan Dergisi',
    giftCards: 'Hediye Kartları',
    contact: 'İletişim',
    trackOrder: 'Sipariş Takibi',
    cart: 'Alışveriş Çantası',
    wishlist: 'Favorilerim',
    searchPlaceholder: 'Abaye adı, nakış veya renk arayın...',
    allAbayas: 'Tüm Abayeler',
    featuredCollection: 'Öne Çıkan Koleksiyon',
    exclusiveCreations: 'Özel Tasarımlarımız',
    details: 'Detaylar',
    addToCart: 'Sepete Ekle',
    buyNow: 'Hemen Satın Al',
    outOfStock: 'Stokta Yok',
    originalColor: 'Orijinal Renk',
    color: 'Renk',
    size: 'Beden',
    sizeGuide: '📏 Akıllı Beden Rehberi',
    productDesc: 'Ürün Açıklaması',
    weightForSize: '⚖️ Beden Ağırlığı',
    relatedProducts: 'Bunları da Beğenebilirsiniz',
    customerReviews: 'Müşteri Değerlendirmeleri',
    noReviewsYet: 'Henüz değerlendirme yok. İlk değerlendiren siz olun!',
    writeReview: '✍️ Değerlendirmenizi Yazın',
    submitReview: 'Gönder',
    yourRating: 'Puanınız:',
    submitting: 'Gönderiliyor...',
    reviewSuccess: '✓ Teşekkürler! Değerlendirmeniz alındı.',
    aiVideoGenerator: '✨ Yapay Zeka Sinematik Video Oluştur (12-15s)',
    generatingVideo: '🎬 Sinematik video oluşturuluyor...',
    videoReady: '✓ Video başarıyla oluşturuldu!',
    bestSellers: 'En Çok Satanlar',
    mostRequested: 'En Popüler',
    bestSellersDesc: 'Değerli müşterilerimizin en çok tercih ettiği tasarımlar',
    whatCustomersSay: 'Müşterilerimiz Ne Diyor',
    viewAll: 'Hepsini Gör',
    expressShipping: 'Dünya Çapında Kargo',
    expressShippingDesc: 'Dünyanın her yerine teslimat yapıyoruz',
    premiumQuality: 'Garanti Kalite',
    premiumQualityDesc: 'Lüks ve birinci sınıf kumaşlar',
    securePayment: 'Güvenli Ödeme',
    securePaymentDesc: 'Tüm ödeme yöntemleri mevcuttur',
    easyReturns: 'Kolay İade',
    easyReturnsDesc: 'Esnek ve kolay iade politikası',
    quickLinks: 'Hızlı Bağlantılar',
    contactUs: 'Bizimle İletişime Geçin',
    newsletter: 'Bülten Aboneliği',
    newsletterDesc: 'Özel teklifler için abone olun:',
    emailPlaceholder: 'E-posta Adresiniz',
    subscribe: 'Abone Ol',
    subscribeSuccess: 'Bültenimize başarıyla abone oldunuz!',
    brandTagline: 'Zahrat Beesan — Zarafeti yansıtan özel tasarımlar ve lüks kumaşlar. Dünya çapında teslimat.',
    allRightsReserved: 'Tüm hakları saklıdır © Zahrat Beesan',
    whatsapp: 'WhatsApp',
    aboutUs: 'Hakkımızda',
    faq: 'SSS',
    gallery: 'Galeri',
    internationalDelivery: 'Uluslararası Teslimat',
    secureCheckout: 'Güvenli Ödeme',
    easyExchange: 'Kolay Değişim',
    emptyCart: 'Çantanız Boş', emptyCartDesc: 'Henüz ürün eklemediniz.', startShopping: 'Alışverişe Başla',
    piece: 'ürün', pieces: 'ürünler', sizeLabel: 'Beden', sendAsGift: '🎁 Hediye Olarak Gönder',
    giftDesc: 'Fildişi lüks ambalaj, Beesan parfümü ve baskılı hediye kartı içerir.',
    giftMsgPlaceholder: 'Hediye kartına yazılacak kişisel mesajınızı yazın...', hidePrices: 'Fiyatları alıcıdan gizle',
    subtotal: 'Ara Toplam', bundleDiscountLabel: 'Paket İndirimi (%10)', deliveryFee: 'Teslimat Ücreti',
    calcAtCheckout: 'Ödeme sırasında hesaplanır', totalLabel: 'Toplam', confirmOrder: 'Siparişi Onayla',
    clearCart: 'Çantayı Temizle', deliveryNoteCart: 'Teslimat ücretleri ödeme sayfasında hesaplanır.',
    wishlistTitle: 'İstek Listesi', productSingular: 'ürün', productPlural: 'ürünler',
    emptyWishlist: 'İstek listeniz boş', emptyWishlistDesc: 'Ürün eklemeye başlayın',
    moveToCart: 'Sepete Ekle', removeItem: 'Kaldır', clearWishlist: 'Hepsini Temizle',
    photosTab: 'Fotoğraflar', videoTab: 'Video', availableColors: 'Mevcut Renkler',
    selectSize: 'Beden Seçin', quantityLabel: 'Miktar', shareProduct: 'Ürünü Paylaş',
    copiedLink: '✓ Bağlantı Kopyalandı!', contactWhatsApp: 'WhatsApp ile İletişim',
    addedToCart: 'Sepete eklendi!', addedToWishlist: 'İstek listesine eklendi!',
    removedFromWishlist: 'İstek listesinden kaldırıldı', selectSizeFirst: 'Lütfen önce beden seçin',
    closeLabel: 'Kapat', save: 'Kaydet', cancel: 'İptal', loading: 'Yükleniyor...', error: 'Hata oluştu', success: 'Başarılı'
  },
  fr: {
    home: 'Accueil',
    collection: 'Collection',
    showcase: 'Galerie',
    magazine: 'Magazine Beesan',
    giftCards: 'Cartes Cadeaux',
    contact: 'Contactez-nous',
    trackOrder: 'Suivre ma commande',
    cart: 'Panier',
    wishlist: 'Favoris',
    searchPlaceholder: 'Rechercher par nom d\'abaya, broderie ou couleur...',
    allAbayas: 'Toutes les Abayas',
    featuredCollection: 'Collection En Vedette',
    exclusiveCreations: 'Nos Créations Exclusives',
    details: 'Détails',
    addToCart: 'Ajouter au Panier',
    buyNow: 'Acheter Maintenant',
    outOfStock: 'Rupture de Stock',
    originalColor: 'Couleur d\'Origine',
    color: 'Couleur',
    size: 'Taille',
    sizeGuide: '📏 Guide des Tailles Intelligent',
    productDesc: 'Description du Produit',
    weightForSize: '⚖️ Poids par Taille',
    relatedProducts: 'Vous Aimerez Aussi',
    customerReviews: 'Avis Clients',
    noReviewsYet: 'Aucun avis pour le moment. Soyez la première à donner votre avis !',
    writeReview: '✍️ Écrire un Avis',
    submitReview: 'Soumettre l\'Avis',
    yourRating: 'Votre Note :',
    submitting: 'Envoi en cours...',
    reviewSuccess: '✓ Merci ! Votre avis a été soumis.',
    aiVideoGenerator: '✨ Générer Vidéo Cinématique IA (12-15s)',
    generatingVideo: '🎬 Génération de la vidéo en cours...',
    videoReady: '✓ Vidéo générée avec succès !',
    bestSellers: 'Meilleures Ventes',
    mostRequested: 'Les Plus Populaires',
    bestSellersDesc: 'Les collections les plus appréciées par nos clientes',
    whatCustomersSay: 'Ce que disent nos clients',
    viewAll: 'Voir Tout',
    expressShipping: 'Livraison Internationale',
    expressShippingDesc: 'Nous livrons dans le monde entier',
    premiumQuality: 'Qualité Garantie',
    premiumQualityDesc: 'Tissus luxueux et haut de gamme',
    securePayment: 'Paiement Sécurisé',
    securePaymentDesc: 'Tous les moyens de paiement acceptés',
    easyReturns: 'Retours Faciles',
    easyReturnsDesc: 'Politique de retour flexible',
    quickLinks: 'Liens Rapides',
    contactUs: 'Contactez-nous',
    newsletter: 'Newsletter',
    newsletterDesc: 'Inscrivez-vous pour des offres exclusives :',
    emailPlaceholder: 'Votre Adresse Email',
    subscribe: 'S\'abonner',
    subscribeSuccess: 'Abonnement réussi à notre newsletter !',
    brandTagline: 'Zahrat Beesan — Des créations exclusives et des tissus luxueux. Livraison dans le monde entier.',
    allRightsReserved: 'Tous droits réservés © Zahrat Beesan',
    whatsapp: 'WhatsApp',
    aboutUs: 'À Propos',
    faq: 'FAQ',
    gallery: 'Galerie',
    internationalDelivery: 'Livraison Mondiale',
    secureCheckout: 'Paiement Sécurisé',
    easyExchange: 'Échange Facile',
    emptyCart: 'Votre Panier est Vide', emptyCartDesc: 'Vous n\'avez pas encore ajouté d\'articles.', startShopping: 'Commencer les Achats',
    piece: 'article', pieces: 'articles', sizeLabel: 'Taille', sendAsGift: '🎁 Envoyer en Cadeau Royal',
    giftDesc: 'Comprend un emballage ivoire luxueux, le parfum Beesan et une carte-cadeau imprimée.',
    giftMsgPlaceholder: 'Écrivez votre message cadeau personnel...', hidePrices: 'Masquer les prix sur la facture',
    subtotal: 'Sous-total', bundleDiscountLabel: 'Remise Lot (10%)', deliveryFee: 'Frais de Livraison',
    calcAtCheckout: 'Calculé à la commande', totalLabel: 'Total', confirmOrder: 'Confirmer la Commande',
    clearCart: 'Vider le Panier', deliveryNoteCart: 'Les frais de livraison sont calculés à la commande.',
    wishlistTitle: 'Liste de Souhaits', productSingular: 'article', productPlural: 'articles',
    emptyWishlist: 'Votre liste de souhaits est vide', emptyWishlistDesc: 'Commencez à ajouter des produits',
    moveToCart: 'Ajouter au Panier', removeItem: 'Supprimer', clearWishlist: 'Tout Effacer',
    photosTab: 'Photos', videoTab: 'Vidéo', availableColors: 'Couleurs Disponibles',
    selectSize: 'Choisir la Taille', quantityLabel: 'Quantité', shareProduct: 'Partager le Produit',
    copiedLink: '✓ Lien Copié!', contactWhatsApp: 'Contacter via WhatsApp',
    addedToCart: 'Ajouté au panier!', addedToWishlist: 'Ajouté aux souhaits!',
    removedFromWishlist: 'Retiré des souhaits', selectSizeFirst: 'Veuillez d\'abord choisir une taille',
    closeLabel: 'Fermer', save: 'Sauvegarder', cancel: 'Annuler', loading: 'Chargement...', error: 'Erreur', success: 'Succès'
  },
  de: {
    home: 'Startseite',
    collection: 'Kollektion',
    showcase: 'Galerie',
    magazine: 'Beesan Magazin',
    giftCards: 'Gutscheine',
    contact: 'Kontakt',
    trackOrder: 'Bestellung Verfolgen',
    cart: 'Warenkorb',
    wishlist: 'Wunschliste',
    searchPlaceholder: 'Suche nach Abaya-Name, Stickerei oder Farbe...',
    allAbayas: 'Alle Abayas',
    featuredCollection: 'Ausgewählte Kollektion',
    exclusiveCreations: 'Unsere Exklusiven Kreationen',
    details: 'Details',
    addToCart: 'In den Warenkorb',
    buyNow: 'Jetzt Kaufen',
    outOfStock: 'Ausverkauft',
    originalColor: 'Originalfarbe',
    color: 'Farbe',
    size: 'Größe',
    sizeGuide: '📏 Intelligenter Größenguide',
    productDesc: 'Produktbeschreibung',
    weightForSize: '⚖️ Gewicht nach Größe',
    relatedProducts: 'Das Könnte Ihnen Auch Gefallen',
    customerReviews: 'Kundenbewertungen',
    noReviewsYet: 'Noch keine Bewertungen. Seien Sie die Erste!',
    writeReview: '✍️ Bewertung Schreiben',
    submitReview: 'Bewertung Absenden',
    yourRating: 'Ihre Bewertung:',
    submitting: 'Wird gesendet...',
    reviewSuccess: '✓ Vielen Dank! Ihre Bewertung wurde übermittelt.',
    aiVideoGenerator: '✨ KI-Kinovideo Erstellen (12-15s)',
    generatingVideo: '🎬 KI-Video wird erstellt...',
    videoReady: '✓ Video erfolgreich erstellt!',
    bestSellers: 'Bestseller',
    mostRequested: 'Sehr Beliebt',
    bestSellersDesc: 'Die beliebtesten Kollektionen unserer geschätzten Kundinnen',
    whatCustomersSay: 'Was unsere Kunden sagen',
    viewAll: 'Alle Anzeigen',
    expressShipping: 'Weltweiter Versand',
    expressShippingDesc: 'Wir liefern weltweit',
    premiumQuality: 'Garantierte Qualität',
    premiumQualityDesc: 'Luxuriöse und hochwertige Stoffe',
    securePayment: 'Sichere Zahlung',
    securePaymentDesc: 'Alle Zahlungsmethoden verfügbar',
    easyReturns: 'Einfache Rückgabe',
    easyReturnsDesc: 'Flexible & einfache Rückgaberegelung',
    quickLinks: 'Quick-Links',
    contactUs: 'Kontaktieren Sie Uns',
    newsletter: 'Newsletter',
    newsletterDesc: 'Abonnieren Sie exklusive Angebote:',
    emailPlaceholder: 'Ihre E-Mail-Adresse',
    subscribe: 'Abonnieren',
    subscribeSuccess: 'Erfolgreich für den Newsletter angemeldet!',
    brandTagline: 'Zahrat Beesan — Exklusive Designs und luxuriöse Stoffe. Weltweiter Versand.',
    allRightsReserved: 'Alle Rechte vorbehalten © Zahrat Beesan',
    whatsapp: 'WhatsApp',
    aboutUs: 'Über Uns',
    faq: 'FAQ',
    gallery: 'Galerie',
    internationalDelivery: 'Weltweite Lieferung',
    secureCheckout: 'Sichere Kasse',
    easyExchange: 'Einfacher Umtausch',
    emptyCart: 'Ihr Warenkorb ist Leer', emptyCartDesc: 'Sie haben noch keine Artikel hinzugefügt.', startShopping: 'Einkaufen Beginnen',
    piece: 'Artikel', pieces: 'Artikel', sizeLabel: 'Größe', sendAsGift: '🎁 Als Königliches Geschenk Senden',
    giftDesc: 'Enthält luxuriöse Elfenbeinverpackung, Beesan-Parfüm und gedruckte Grußkarte.',
    giftMsgPlaceholder: 'Schreiben Sie Ihre persönliche Geschenkbotschaft...', hidePrices: 'Preise auf Rechnung ausblenden',
    subtotal: 'Zwischensumme', bundleDiscountLabel: 'Paketrabatt (10%)', deliveryFee: 'Liefergebühr',
    calcAtCheckout: 'Wird beim Checkout berechnet', totalLabel: 'Gesamtsumme', confirmOrder: 'Bestellung Bestätigen',
    clearCart: 'Warenkorb Leeren', deliveryNoteCart: 'Liefergebühren werden beim Checkout berechnet.',
    wishlistTitle: 'Wunschliste', productSingular: 'Artikel', productPlural: 'Artikel',
    emptyWishlist: 'Ihre Wunschliste ist leer', emptyWishlistDesc: 'Beginnen Sie Produkte hinzuzufügen',
    moveToCart: 'In den Warenkorb', removeItem: 'Entfernen', clearWishlist: 'Alle Löschen',
    photosTab: 'Fotos', videoTab: 'Video', availableColors: 'Verfügbare Farben',
    selectSize: 'Größe Wählen', quantityLabel: 'Menge', shareProduct: 'Produkt Teilen',
    copiedLink: '✓ Link Kopiert!', contactWhatsApp: 'Über WhatsApp Kontaktieren',
    addedToCart: 'Zum Warenkorb hinzugefügt!', addedToWishlist: 'Zur Wunschliste hinzugefügt!',
    removedFromWishlist: 'Von der Wunschliste entfernt', selectSizeFirst: 'Bitte wählen Sie zuerst eine Größe',
    closeLabel: 'Schließen', save: 'Speichern', cancel: 'Abbrechen', loading: 'Laden...', error: 'Fehler', success: 'Erfolg'
  },
  ru: {
    home: 'Главная',
    collection: 'Коллекция',
    showcase: 'Галерея',
    magazine: 'Журнал Beesan',
    giftCards: 'Подарочные карты',
    contact: 'Контакты',
    trackOrder: 'Отследить заказ',
    cart: 'Корзина',
    wishlist: 'Избранное',
    searchPlaceholder: 'Поиск по названию абайи, вышивке или цвету...',
    allAbayas: 'Все Абайи',
    featuredCollection: 'Рекомендуемая коллекция',
    exclusiveCreations: 'Наши Эксклюзивные Модели',
    details: 'Подробнее',
    addToCart: 'В корзину',
    buyNow: 'Купить сейчас',
    outOfStock: 'Нет в наличии',
    originalColor: 'Исходный цвет',
    color: 'Цвет',
    size: 'Размер',
    sizeGuide: '📏 Умный гид по размерам',
    productDesc: 'Описание товара',
    weightForSize: '⚖️ Вес для размера',
    relatedProducts: 'Вам также может понравиться',
    customerReviews: 'Отзывы покупателей',
    noReviewsYet: 'Отзывов пока нет. Будьте первыми!',
    writeReview: '✍️ Написать отзыв',
    submitReview: 'Отправить отзыв',
    yourRating: 'Ваша оценка:',
    submitting: 'Отправка...',
    reviewSuccess: '✓ Спасибо! Ваш отзыв успешно отправлен.',
    aiVideoGenerator: '✨ Создать ИИ-видео (12-15с)',
    generatingVideo: '🎬 Создание видео ИИ...',
    videoReady: '✓ Видео успешно создано!',
    bestSellers: 'Хиты Продаж',
    mostRequested: 'Популярное',
    bestSellersDesc: 'Коллекции, получившие наибольшее количество отзывов',
    whatCustomersSay: 'Отзывы Наших Клиентов',
    viewAll: 'Посмотреть Все',
    expressShipping: 'Доставка по всему миру',
    expressShippingDesc: 'Доставляем во все страны мира',
    premiumQuality: 'Гарантия Качества',
    premiumQualityDesc: 'Роскошные ткани высочайшего качества',
    securePayment: 'Безопасная Оплата',
    securePaymentDesc: 'Все способы оплаты доступны',
    easyReturns: 'Простой Возврат',
    easyReturnsDesc: 'Гибкие условия возврата и обмена',
    quickLinks: 'Быстрые Ссылки',
    contactUs: 'Связаться с Нами',
    newsletter: 'Рассылка',
    newsletterDesc: 'Подпишитесь на эксклюзивные скидки:',
    emailPlaceholder: 'Ваш Email',
    subscribe: 'Подписаться',
    subscribeSuccess: 'Вы успешно подписались на рассылку!',
    brandTagline: 'Zahrat Beesan — Эксклюзивный дизайн и роскошные ткани. Доставка по всему миру.',
    allRightsReserved: 'Все права защищены © Zahrat Beesan',
    whatsapp: 'WhatsApp',
    aboutUs: 'О нас',
    faq: 'Частые вопросы',
    gallery: 'Галерея',
    internationalDelivery: 'Международная доставка',
    secureCheckout: 'Безопасная оплата',
    easyExchange: 'Легкий обмен',
    emptyCart: 'Ваша корзина пуста', emptyCartDesc: 'Вы ещё не добавили ни одного товара.', startShopping: 'Начать покупки',
    piece: 'товар', pieces: 'товаров', sizeLabel: 'Размер', sendAsGift: '🎁 Отправить как Королевский Подарок',
    giftDesc: 'Включает роскошную упаковку, парфюм Beesan и именную открытку.',
    giftMsgPlaceholder: 'Напишите ваше личное пожелание для открытки...', hidePrices: 'Скрыть цены в счете',
    subtotal: 'Промежуточный итог', bundleDiscountLabel: 'Скидка за набор (10%)', deliveryFee: 'Стоимость доставки',
    calcAtCheckout: 'Рассчитывается при оформлении', totalLabel: 'Итого', confirmOrder: 'Подтвердить заказ',
    clearCart: 'Очистить корзину', deliveryNoteCart: 'Стоимость доставки рассчитывается при оформлении.',
    wishlistTitle: 'Список желаний', productSingular: 'товар', productPlural: 'товаров',
    emptyWishlist: 'Список желаний пуст', emptyWishlistDesc: 'Начните добавлять товары в список',
    moveToCart: 'В корзину', removeItem: 'Удалить', clearWishlist: 'Очистить всё',
    photosTab: 'Фото', videoTab: 'Видео', availableColors: 'Доступные цвета',
    selectSize: 'Выбрать размер', quantityLabel: 'Количество', shareProduct: 'Поделиться',
    copiedLink: '✓ Ссылка скопирована!', contactWhatsApp: 'Связаться через WhatsApp',
    addedToCart: 'Добавлено в корзину!', addedToWishlist: 'Добавлено в список желаний!',
    removedFromWishlist: 'Удалено из списка желаний', selectSizeFirst: 'Пожалуйста, сначала выберите размер',
    closeLabel: 'Закрыть', save: 'Сохранить', cancel: 'Отмена', loading: 'Загрузка...', error: 'Ошибка', success: 'Успешно'
  },
  es: {
    home: 'Inicio',
    collection: 'Colección',
    showcase: 'Galería',
    magazine: 'Revista Beesan',
    giftCards: 'Tarjetas de Regalo',
    contact: 'Contacto',
    trackOrder: 'Rastrear Pedido',
    cart: 'Bolsa de Compras',
    wishlist: 'Lista de Deseos',
    searchPlaceholder: 'Buscar por nombre de abaya, bordado o color...',
    allAbayas: 'Todas las Abayas',
    featuredCollection: 'Colección Destacada',
    exclusiveCreations: 'Nuestras Creaciones Exclusivas',
    details: 'Detalles',
    addToCart: 'Añadir al Carrito',
    buyNow: 'Comprar Ahora',
    outOfStock: 'Agotado',
    originalColor: 'Color Original',
    color: 'Color',
    size: 'Talla',
    sizeGuide: '📏 Guía Inteligente de Tallas',
    productDesc: 'Descripción del Producto',
    weightForSize: '⚖️ Peso por Talla',
    relatedProducts: 'También Te Puede Gustar',
    customerReviews: 'Opiniones de Clientes',
    noReviewsYet: 'Aún no hay opiniones. ¡Sé la primera en opinar!',
    writeReview: '✍️ Escribir una Opinión',
    submitReview: 'Enviar Opinión',
    yourRating: 'Tu Valoración:',
    submitting: 'Enviando...',
    reviewSuccess: '✓ ¡Gracias! Tu opinión ha sido enviada.',
    aiVideoGenerator: '✨ Generar Video IA Cinematográfico (12-15s)',
    generatingVideo: '🎬 Generando video cinematográfico IA...',
    videoReady: '✓ ¡Video generado con éxito!',
    bestSellers: 'Más Vendidos',
    mostRequested: 'Más Populares',
    bestSellersDesc: 'Colecciones destacadas elegidas por nuestras clientas',
    whatCustomersSay: 'Lo Que Dicen Nuestros Clientes',
    viewAll: 'Ver Todo',
    expressShipping: 'Envío Internacional',
    expressShippingDesc: 'Enviamos a todo el mundo',
    premiumQuality: 'Calidad Garantizada',
    premiumQualityDesc: 'Tejidos lujosos de alta calidad',
    securePayment: 'Pago Seguro',
    securePaymentDesc: 'Todos los métodos de pago disponibles',
    easyReturns: 'Devoluciones Fáciles',
    easyReturnsDesc: 'Política de devolución flexible',
    quickLinks: 'Enlaces Rápidos',
    contactUs: 'Contáctanos',
    newsletter: 'Boletín Informativo',
    newsletterDesc: 'Suscríbete para ofertas exclusivas:',
    emailPlaceholder: 'Tu Correo Electrónico',
    subscribe: 'Suscribirse',
    subscribeSuccess: '¡Suscripción al boletín completada con éxito!',
    brandTagline: 'Zahrat Beesan — Diseños exclusivos y telas lujosas. Envío a todo el mundo.',
    allRightsReserved: 'Todos los derechos reservados © Zahrat Beesan',
    whatsapp: 'WhatsApp',
    aboutUs: 'Sobre Nosotros',
    faq: 'Preguntas Frecuentes',
    gallery: 'Galería',
    internationalDelivery: 'Envío Global',
    secureCheckout: 'Pago Seguro',
    easyExchange: 'Cambio Fácil',
    emptyCart: 'Tu Bolsa está Vacía', emptyCartDesc: 'Aún no has añadido artículos a tu bolsa.', startShopping: 'Comenzar Compras',
    piece: 'artículo', pieces: 'artículos', sizeLabel: 'Talla', sendAsGift: '🎁 Enviar como Regalo Real',
    giftDesc: 'Incluye embalaje de marfil de lujo, perfume Beesan y tarjeta de regalo impresa.',
    giftMsgPlaceholder: 'Escribe tu mensaje personal para la tarjeta de regalo...', hidePrices: 'Ocultar precios en la factura',
    subtotal: 'Subtotal', bundleDiscountLabel: 'Descuento Paquete (10%)', deliveryFee: 'Gastos de Envío',
    calcAtCheckout: 'Calculado en el pago', totalLabel: 'Total', confirmOrder: 'Confirmar Pedido',
    clearCart: 'Vaciar Bolsa', deliveryNoteCart: 'Los gastos de envío se calculan en el pago.',
    wishlistTitle: 'Lista de Deseos', productSingular: 'artículo', productPlural: 'artículos',
    emptyWishlist: 'Tu lista de deseos está vacía', emptyWishlistDesc: 'Comienza a agregar productos',
    moveToCart: 'Añadir a la Bolsa', removeItem: 'Eliminar', clearWishlist: 'Limpiar Todo',
    photosTab: 'Fotos', videoTab: 'Video', availableColors: 'Colores Disponibles',
    selectSize: 'Seleccionar Talla', quantityLabel: 'Cantidad', shareProduct: 'Compartir Producto',
    copiedLink: '✓ ¡Enlace Copiado!', contactWhatsApp: 'Contactar por WhatsApp',
    addedToCart: '¡Añadido a la bolsa!', addedToWishlist: '¡Añadido a favoritos!',
    removedFromWishlist: 'Eliminado de favoritos', selectSizeFirst: 'Por favor selecciona una talla primero',
    closeLabel: 'Cerrar', save: 'Guardar', cancel: 'Cancelar', loading: 'Cargando...', error: 'Error', success: 'Éxito'
  },
  ur: {
    home: 'ہوم',
    collection: 'کلیکشن',
    showcase: 'گئیلری',
    magazine: 'بیسان میگزین',
    giftCards: 'گفٹ کارڈز',
    contact: 'ہم سے رابطہ کریں',
    trackOrder: 'آرڈر ٹریک کریں',
    cart: 'خریداری کا تھیلا',
    wishlist: 'پسندیدہ',
    searchPlaceholder: 'عبایا کے نام، کڑھائی یا رنگ سے تلاش کریں...',
    allAbayas: 'تمام عبایاجات',
    featuredCollection: 'خاص کلیکشن',
    exclusiveCreations: 'ہماری خصوصیات',
    details: 'تفصیلات',
    addToCart: 'کارٹ میں شامل کریں',
    buyNow: 'ابھی خریدیں',
    outOfStock: 'اسٹاک میں نہیں ہے',
    originalColor: 'اصل رنگ',
    color: 'رنگ',
    size: 'سائز',
    sizeGuide: '📏 سائز گائیڈ',
    productDesc: 'پروڈکٹ کی تفصیل',
    weightForSize: '⚖️ سائز کا وزن',
    relatedProducts: 'آپ کو یہ بھی پسند آ سکتا ہے',
    customerReviews: 'کسٹمر کے جائزے',
    noReviewsYet: 'ابھی تک کوئی جائزے۔ پہلے جائزہ نگار بنیں!',
    writeReview: '✍️ اپنا جائزہ لکھیں',
    submitReview: 'جائزہ جمع کروائیں',
    yourRating: 'آپ کی درجہ بندی:',
    submitting: 'ارسال ہو رہا ہے...',
    reviewSuccess: '✓ شکریہ! آپ کا جائزہ جمع کر دیا گیا ہے۔',
    aiVideoGenerator: '✨ AI سنیمیٹک ویڈیو بنائیں۔ (12-15 سیکنڈ)',
    generatingVideo: '🎬 ویڈیو بنائی جا رہی ہے...',
    videoReady: '✓ ویڈیو کامیابی سے بن گئی!',
    bestSellers: 'بہترین ترسیل',
    mostRequested: 'سب سے زیادہ مقبول',
    bestSellersDesc: 'ہمارے گاہکوں کے سب سے پسندیدہ کلیکشنز',
    whatCustomersSay: 'ہمارے صارفین کا کیا کہنا ہے',
    viewAll: 'سب دیکھیں',
    expressShipping: 'عالمی ترسیل',
    expressShippingDesc: 'ہم پوری دنیا میں ترسیل کرتے ہیں',
    premiumQuality: 'ضمانت شدہ معیار',
    premiumQualityDesc: 'اعلیٰ اور فخر کپڑے',
    securePayment: 'محفوظ ادائیگی',
    securePaymentDesc: 'تمام ادائیگی کے طریقے دستیاب ہیں',
    easyReturns: 'آسان واپسی',
    easyReturnsDesc: 'لچکدار اور آسان واپسی کی پالیسی',
    quickLinks: 'فوری لنکس',
    contactUs: 'ہم سے رابطہ کریں',
    newsletter: 'خبرنامہ',
    newsletterDesc: 'خصوصی پیشکشیں حاصل کرنے کے لیے سبسکرائب کریں:',
    emailPlaceholder: 'آپ کا ای میل پتہ',
    subscribe: 'سبسکرائب کریں',
    subscribeSuccess: 'خبرنامے کی رکنیت کامیابی سے حاصل ہو گئی!',
    brandTagline: 'زہرہ بیسان — خوبصورتی کی عکاسی کرنے والے خصوصی ڈیزائنز۔ عالمی ترسیل۔',
    allRightsReserved: 'جملہ حقوق محفوظ ہیں © زہرہ بیسان',
    whatsapp: 'واٹس ایپ',
    aboutUs: 'ہمارے بارے میں',
    faq: 'عام سوالات',
    gallery: 'گیلری',
    internationalDelivery: 'بین الاقوامی ترسیل',
    secureCheckout: 'محفوظ چیک آؤٹ',
    easyExchange: 'آسان تبدیلی',
    emptyCart: 'آپ کا بیگ خالی ہے', emptyCartDesc: 'آپ نے ابھی تک کوئی مصنوع نہیں ڈالا۔', startShopping: 'خریداری شروع کریں',
    piece: 'مصنوع', pieces: 'مصنوعات', sizeLabel: 'سائز', sendAsGift: '🎁 شاہی تحفہ کے طور پر بھیجیں',
    giftDesc: 'عاجی لگژری پیکیجنگ، بیسان خوشبو اور تحریری کارڈ شامل ہے۔',
    giftMsgPlaceholder: 'تحفہ کارڈ کے لیے اپنا ذاتی پیغام لکھیں...', hidePrices: 'وصول کنندہ کو قیمتیں چھپائیں',
    subtotal: 'ذیلی کل', bundleDiscountLabel: 'بنڈل ڈسکاؤنٹ (10%)', deliveryFee: 'ترسیل فیس',
    calcAtCheckout: 'ادائیگی پر حساب', totalLabel: 'کل رقم', confirmOrder: 'آرڈر تصدیق کریں',
    clearCart: 'بیگ صاف کریں', deliveryNoteCart: 'ترسیل فیس ادائیگی صفحے پر حساب کی جاتی ہے۔',
    wishlistTitle: 'خواہشات کی فہرست', productSingular: 'مصنوع', productPlural: 'مصنوعات',
    emptyWishlist: 'خواہشات کی فہرست خالی ہے', emptyWishlistDesc: 'مصنوعات شامل کرنا شروع کریں',
    moveToCart: 'بیگ میں شامل کریں', removeItem: 'ہٹائیں', clearWishlist: 'سب صاف کریں',
    photosTab: 'تصاویر', videoTab: 'ویڈیو', availableColors: 'دستیاب رنگ',
    selectSize: 'سائز منتخب کریں', quantityLabel: 'مقدار', shareProduct: 'مصنوع شیئر کریں',
    copiedLink: '✓ لنک کاپی ہو گیا!', contactWhatsApp: 'واٹس ایپ پر رابطہ',
    addedToCart: 'بیگ میں شامل کیا!', addedToWishlist: 'خواہشات میں شامل کیا!',
    removedFromWishlist: 'خواہشات سے ہٹایا گیا', selectSizeFirst: 'پہلے سائز منتخب کریں',
    closeLabel: 'بند کریں', save: 'محفوظ کریں', cancel: 'منسوخ', loading: 'لوڈ ہو رہا ہے...', error: 'خطا', success: 'کامیاب'
  },
  it: {
    home: 'Home',
    collection: 'Collezione',
    showcase: 'Galleria',
    magazine: 'Rivista Beesan',
    giftCards: 'Carte Regalo',
    contact: 'Contattaci',
    trackOrder: 'Traccia Ordine',
    cart: 'Carrello',
    wishlist: 'Lista dei Desideri',
    searchPlaceholder: 'Cerca per nome abaya, ricamo o colore...',
    allAbayas: 'Tutte le Abaya',
    featuredCollection: 'Collezione In Evidenza',
    exclusiveCreations: 'Le Nostre Creazioni Esclusive',
    details: 'Dettagli',
    addToCart: 'Aggiungi al Carrello',
    buyNow: 'Acquista Ora',
    outOfStock: 'Esaurito',
    originalColor: 'Colore Originale',
    color: 'Colore',
    size: 'Taglia',
    sizeGuide: '📏 Guida Intelligente alle Taglie',
    productDesc: 'Descrizione Prodotto',
    weightForSize: '⚖️ Peso per Taglia',
    relatedProducts: 'Potrebbe Piacerti Anche',
    customerReviews: 'Recensioni Clienti',
    noReviewsYet: 'Nessuna recensione. Sii la prima a recensire questo prodotto!',
    writeReview: '✍️ Scrivi una Recensione',
    submitReview: 'Invia Recensione',
    yourRating: 'La Tua Valutazione:',
    submitting: 'Invio in corso...',
    reviewSuccess: '✓ Grazie! La tua recensione è stata inviata.',
    aiVideoGenerator: '✨ Genera Video IA Cinematografico (12-15s)',
    generatingVideo: '🎬 Generazione video IA in corso...',
    videoReady: '✓ Video generato con successo!',
    bestSellers: 'I Più Venduti',
    mostRequested: 'I Più Richiesti',
    bestSellersDesc: 'Le collezioni più amate dalle nostre clienti',
    whatCustomersSay: 'Cosa Dicono i Nostri Clienti',
    viewAll: 'Vedi Tutti',
    expressShipping: 'Spedizione Mondiale',
    expressShippingDesc: 'Consegniamo in tutto il mondo',
    premiumQuality: 'Qualità Garantita',
    premiumQualityDesc: 'Tessuti lussuosi di prima scelta',
    securePayment: 'Pagamento Sicuro',
    securePaymentDesc: 'Tutti i metodi di pagamento disponibili',
    easyReturns: 'Reso Facile',
    easyReturnsDesc: 'Politica di reso semplice e flessibile',
    quickLinks: 'Link Rapidi',
    contactUs: 'Contattaci',
    newsletter: 'Newsletter',
    newsletterDesc: 'Iscriviti per offerte esclusive:',
    emailPlaceholder: 'La Tua Email',
    subscribe: 'Iscriviti',
    subscribeSuccess: 'Iscrizione alla newsletter riuscita!',
    brandTagline: 'Zahrat Beesan — Design esclusivi e tessuti lussuosi. Spedizione in tutto il mondo.',
    allRightsReserved: 'Tutti i diritti riservati © Zahrat Beesan',
    whatsapp: 'WhatsApp',
    aboutUs: 'Chi Siamo',
    faq: 'FAQ',
    gallery: 'Galleria',
    internationalDelivery: 'Consegna Globale',
    secureCheckout: 'Cassa Sicura',
    easyExchange: 'Cambio Facile',
    emptyCart: 'La Tua Borsa è Vuota', emptyCartDesc: 'Non hai ancora aggiunto articoli.', startShopping: 'Inizia gli Acquisti',
    piece: 'articolo', pieces: 'articoli', sizeLabel: 'Taglia', sendAsGift: '🎁 Invia come Regalo Reale',
    giftDesc: 'Include imballaggio avorio di lusso, profumo Beesan e biglietto regalo stampato.',
    giftMsgPlaceholder: 'Scrivi il tuo messaggio personale per il biglietto regalo...', hidePrices: 'Nascondi prezzi in fattura',
    subtotal: 'Subtotale', bundleDiscountLabel: 'Sconto Bundle (10%)', deliveryFee: 'Spese di Consegna',
    calcAtCheckout: 'Calcolato al pagamento', totalLabel: 'Totale', confirmOrder: 'Conferma Ordine',
    clearCart: 'Svuota Borsa', deliveryNoteCart: 'Le spese di consegna vengono calcolate al pagamento.',
    wishlistTitle: 'Lista dei Desideri', productSingular: 'articolo', productPlural: 'articoli',
    emptyWishlist: 'La tua lista dei desideri è vuota', emptyWishlistDesc: 'Inizia ad aggiungere prodotti',
    moveToCart: 'Aggiungi alla Borsa', removeItem: 'Rimuovi', clearWishlist: 'Cancella Tutto',
    photosTab: 'Foto', videoTab: 'Video', availableColors: 'Colori Disponibili',
    selectSize: 'Seleziona Taglia', quantityLabel: 'Quantità', shareProduct: 'Condividi Prodotto',
    copiedLink: '✓ Link Copiato!', contactWhatsApp: 'Contatta via WhatsApp',
    addedToCart: 'Aggiunto alla borsa!', addedToWishlist: 'Aggiunto ai desideri!',
    removedFromWishlist: 'Rimosso dai desideri', selectSizeFirst: 'Seleziona prima una taglia',
    closeLabel: 'Chiudi', save: 'Salva', cancel: 'Annulla', loading: 'Caricamento...', error: 'Errore', success: 'Successo'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [langCode, setLangCode] = useState(() => {
    return localStorage.getItem('app_language') || 'ar';
  });

  const currentLang = LANGUAGES.find(l => l.code === langCode) || LANGUAGES[0];

  useEffect(() => {
    localStorage.setItem('app_language', langCode);
    document.documentElement.lang = langCode;
    document.documentElement.dir = currentLang ? currentLang.dir : 'rtl';
  }, [langCode, currentLang]);

  const productDictionary = {
    en: {
      'عباية': 'Abaya', 'عبايات': 'Abayas', 'ثوب': 'Thobe', 'أثواب': 'Thobes', 'قفطان': 'Kaftan', 'قفاطين': 'Kaftans', 'حرير': 'Silk',
      'ملكي': 'Royal', 'الملكي': 'Royal', 'الملكية': 'Royal', 'عرائسي': 'Bridal', 'العرائس': 'Bridal',
      'فاخر': 'Luxury', 'فاخرة': 'Luxury', 'مطرز': 'Embroidered', 'مطرزة': 'Embroidered',
      'كلاسيك': 'Classic', 'كلاسيكية': 'Classic', 'عصرية': 'Modern', 'مناسبات': 'Occasions',
      'استقبال': 'Reception', 'يومية': 'Daily', 'شتوية': 'Winter', 'صيفية': 'Summer',
      'بشت': 'Bisht', 'سوداء': 'Black', 'عاجية': 'Ivory', 'الأناقة': 'Elegance',
      'السلطانة': 'Sultana', 'الأميرة': 'Princess', 'تاج': 'Crown', 'الياقوتة': 'Sapphire',
      'اللؤلؤة': 'Pearl', 'بيسان': 'Beesan', 'اليشمك': 'Yashmak', 'الأندلس': 'Andalus',
      'نوع القماش': 'Fabric Type', 'كريب فاخر': 'Luxury Crepe', 'بلد المنشأ': 'Country of Origin',
      'الأردن': 'Jordan', 'غسيل يدوي بماء بارد': 'Hand wash with cold water', 'كي على حرارة منخفضة': 'Low heat ironing'
    },
    tr: {
      'عباية': 'Abaye', 'ثوب': 'Elbise', 'قفطان': 'Kaftan', 'حرير': 'İpek', 'ملكي': 'Kraliyet',
      'الملكي': 'Kraliyet', 'فاخر': 'Lüks', 'مطرز': 'İşlemeli', 'كلاسيك': 'Klasik', 'عصرية': 'Modern'
    },
    fr: {
      'عباية': 'Abaya', 'ثوب': 'Robe', 'قفطان': 'Caftan', 'حرير': 'Soie', 'ملكي': 'Royal',
      'الملكي': 'Royal', 'فاخر': 'De Luxe', 'مطرز': 'Brodé', 'كلاسيك': 'Classique', 'عصرية': 'Moderne'
    },
    de: {
      'عباية': 'Abaya', 'ثوب': 'Kleidung', 'قفطان': 'Kaftan', 'حرير': 'Seide', 'ملكي': 'Königlich',
      'فاخر': 'Luxus', 'مطرز': 'Gestickt', 'كلاسيك': 'Klassisch', 'عصرية': 'Modern'
    },
    ru: {
      'عباية': 'Абая', 'ثوب': 'Платье', 'قفطان': 'Кафтан', 'حرير': 'Шелк', 'ملكي': 'Королевский',
      'فاخر': 'Роскошный', 'مطرز': 'Вышитый', 'كلاسيك': 'Классический', 'عصرية': 'Современная'
    },
    es: {
      'عباية': 'Abaya', 'ثوب': 'Túnica', 'قفطان': 'Caftán', 'حرير': 'Seda', 'ملكي': 'Real',
      'فاخر': 'Lujo', 'مطرز': 'Bordado', 'كلاسيك': 'Clásico', 'عصرية': 'Moderna'
    },
    ur: {
      'عباية': 'عبایا', 'ثوب': 'ثوب', 'قفطان': 'قفطان', 'حرير': 'ریشم', 'ملكي': 'شاہی',
      'فاخر': 'فاخر', 'مطرز': 'کڑھائی', 'كلاسيك': 'کلاسیکی'
    },
    it: {
      'عباية': 'Abaya', 'ثوب': 'Tuba', 'قفطان': 'Caftano', 'حرير': 'Seta', 'ملكي': 'Reale',
      'فاخر': 'Lusso', 'مطرز': 'Ricamato', 'كلاسيك': 'Classico'
    }
  };

  const tProduct = (str) => {
    if (!str || typeof str !== 'string' || langCode === 'ar') return str;
    const dict = productDictionary[langCode] || productDictionary['en'];
    let translated = str;
    Object.keys(dict).forEach(arKey => {
      const regex = new RegExp(arKey, 'g');
      translated = translated.replace(regex, dict[arKey]);
    });
    return translated;
  };

  const t = (key) => {
    return translations[langCode]?.[key] || translations['ar']?.[key] || key;
  };

  const changeLanguage = (code) => {
    if (LANGUAGES.some(l => l.code === code)) {
      setLangCode(code);
    }
  };

  return (
    <LanguageContext.Provider value={{ langCode, currentLang, changeLanguage, t, tProduct, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
